#ifndef XBOXKRNL_API_XBOX_H
#define XBOXKRNL_API_XBOX_H

XBAPI PLAUNCH_DATA_PAGE LaunchDataPage;

XBAPI XBOX_KEY_DATA XboxAlternateSignatureKeys[];

XBAPI XBOX_KEY_DATA XboxEEPROMKey;

XBAPI XBOX_HARDWARE_INFO XboxHardwareInfo;

XBAPI XBOX_KEY_DATA XboxHDKey;

XBAPI XBOX_KRNL_VERSION XboxKrnlVersion;

XBAPI XBOX_KEY_DATA XboxLANKey;

XBAPI XBOX_KEY_DATA XboxSignatureKey;

#endif
